-- Add species data for Atlantique and Manche fishing zones
-- Atlantique species
INSERT INTO public.species (name, fishing_area, fishing_gear) VALUES
-- Poissons blancs Atlantique
('Bar commun', 'atlantique', 'ligne,filet,chalut,palangre'),
('Bar moucheté', 'atlantique', 'ligne,filet,chalut'),
('Sole commune', 'atlantique', 'filet,chalut'),
('Turbot', 'atlantique', 'filet,chalut,palangre'),
('Barbue', 'atlantique', 'filet,chalut'),
('Lieu jaune', 'atlantique', 'ligne,filet,chalut,palangre'),
('Lieu noir', 'atlantique', 'ligne,filet,chalut'),
('Merlu', 'atlantique', 'chalut,filet,palangre'),
('Colin', 'atlantique', 'chalut,filet'),
('Cabillaud', 'atlantique', 'chalut,filet,palangre,ligne'),
('Églefin', 'atlantique', 'chalut,filet,palangre'),
('Merlan', 'atlantique', 'chalut,filet'),
('Raie bouclée', 'atlantique', 'chalut,filet'),
('Raie brunette', 'atlantique', 'chalut,filet'),
('Saint-Pierre', 'atlantique', 'chalut,filet'),
('Congre', 'atlantique', 'palangre,filet,casier'),
('Lingue', 'atlantique', 'palangre,chalut'),
('Julienne', 'atlantique', 'palangre,chalut'),
('Tacaud', 'atlantique', 'chalut,filet,ligne'),
('Grondin rouge', 'atlantique', 'chalut,filet'),
('Grondin perlon', 'atlantique', 'chalut,filet'),
('Carrelet', 'atlantique', 'filet,chalut'),
('Limande', 'atlantique', 'filet,chalut'),
('Limande-sole', 'atlantique', 'filet,chalut'),
('Céteau', 'atlantique', 'filet,chalut'),
('Plie', 'atlantique', 'filet,chalut'),
-- Poissons bleus Atlantique
('Maquereau', 'atlantique', 'ligne,filet,senne,chalut'),
('Sardine', 'atlantique', 'senne,filet'),
('Chinchard', 'atlantique', 'chalut,senne,ligne'),
('Anchois', 'atlantique', 'senne,filet'),
('Thon germon', 'atlantique', 'ligne,palangre'),
('Bonite à dos rayé', 'atlantique', 'ligne,senne'),
('Hareng', 'atlantique', 'chalut,senne,filet'),
-- Crustacés Atlantique
('Langoustine', 'atlantique', 'casier,chalut'),
('Homard européen', 'atlantique', 'casier'),
('Tourteau', 'atlantique', 'casier,filet'),
('Araignée de mer', 'atlantique', 'casier,filet'),
('Étrille', 'atlantique', 'casier,filet'),
('Crevette rose', 'atlantique', 'chalut,casier'),
('Crevette grise', 'atlantique', 'chalut,filet'),
('Bouquet', 'atlantique', 'casier,filet'),
('Langouste rouge', 'atlantique', 'casier,filet'),
-- Coquillages Atlantique
('Huître creuse', 'atlantique', 'drague'),
('Huître plate', 'atlantique', 'drague'),
('Moule de bouchot', 'atlantique', 'drague'),
('Coquille Saint-Jacques', 'atlantique', 'drague'),
('Pétoncle', 'atlantique', 'drague,chalut'),
('Palourde', 'atlantique', 'drague'),
('Praire', 'atlantique', 'drague'),
('Coque', 'atlantique', 'drague'),
('Couteau', 'atlantique', 'drague'),
('Amande de mer', 'atlantique', 'drague,chalut'),
('Bulot', 'atlantique', 'casier'),
('Bigorneau', 'atlantique', 'casier'),
-- Céphalopodes Atlantique
('Seiche', 'atlantique', 'casier,filet,chalut'),
('Encornet', 'atlantique', 'chalut,ligne'),
('Poulpe', 'atlantique', 'casier,filet'),

-- Manche species
-- Poissons Manche
('Bar commun', 'manche', 'ligne,filet,chalut'),
('Sole commune', 'manche', 'filet,chalut'),
('Turbot', 'manche', 'filet,chalut'),
('Barbue', 'manche', 'filet,chalut'),
('Lieu jaune', 'manche', 'ligne,chalut,filet'),
('Cabillaud', 'manche', 'chalut,filet,ligne'),
('Merlan', 'manche', 'chalut,filet'),
('Carrelet', 'manche', 'filet,chalut'),
('Limande', 'manche', 'filet,chalut'),
('Flétan', 'manche', 'chalut,palangre'),
('Plie', 'manche', 'filet,chalut'),
('Raie bouclée', 'manche', 'chalut,filet'),
('Roussette', 'manche', 'filet,palangre'),
('Saint-Pierre', 'manche', 'chalut,filet'),
('Tacaud', 'manche', 'chalut,filet,ligne'),
('Vieille', 'manche', 'casier,ligne,filet'),
('Grondin rouge', 'manche', 'chalut,filet'),
('Congre', 'manche', 'palangre,filet,casier'),
-- Poissons bleus Manche
('Maquereau', 'manche', 'ligne,filet,senne'),
('Hareng', 'manche', 'chalut,senne,filet'),
('Sardine', 'manche', 'senne,filet'),
('Sprat', 'manche', 'senne,filet,chalut'),
-- Crustacés Manche
('Homard européen', 'manche', 'casier'),
('Tourteau', 'manche', 'casier,filet'),
('Araignée de mer', 'manche', 'casier,filet'),
('Étrille', 'manche', 'casier,filet'),
('Crevette grise', 'manche', 'chalut,filet'),
('Bouquet', 'manche', 'casier,filet'),
('Dormeur', 'manche', 'casier'),
-- Coquillages Manche
('Coquille Saint-Jacques', 'manche', 'drague'),
('Pétoncle noir', 'manche', 'drague'),
('Moule de bouchot', 'manche', 'drague'),
('Huître creuse', 'manche', 'drague'),
('Huître plate', 'manche', 'drague'),
('Palourde', 'manche', 'drague'),
('Praire', 'manche', 'drague'),
('Bulot', 'manche', 'casier'),
('Ormeau', 'manche', 'plongée'),
('Coque', 'manche', 'drague'),
-- Céphalopodes Manche
('Seiche', 'manche', 'casier,filet,chalut'),
('Encornet', 'manche', 'chalut,ligne'),
('Poulpe', 'manche', 'casier,filet')
ON CONFLICT DO NOTHING;